### ISSUE TITLE
Callback function is returning the last value stored in QR code

### ISSUE THREAD

**Issue by UmairYasin** [hadeeb/simple-barcode-scanner#1]
I am creating QR code by using a UUID format and while scanning it using this plugin, it always returns me the last part of UUID i.e after last '-' in UUID format.  e.g if UUID is
18d0b263-9adb-4ba5-8df8-f4a7f5a9fdba 
then the callback is returning 
f4a7f5a9fdba only.

**Comment by hadeeb** [comment]
By default '-' is not considered as a valid key.

When initiating the scanner, you should pass a regex for valid keys.

In your case, something like

`
const scanner = BarcodeScanner({validKey:/^[a-zA-Z0-9\-]$/});
`
