### ISSUE TITLE
Is it possible to identify the scanner device?

### ISSUE THREAD

**Issue by denyncrawford** [hadeeb/simple-barcode-scanner#12]
I was trying to use the scanner with `node-hid` but it doesn't support keyboard devices. Then I came across this module.
My problem is that I need to use this for multiple devices in production with the same PC and I need a way to determine the device source of the event being emitted.
I know that due to the way the module is made it is not possible to know the input source device directly from the process, but I was wondering if there could be a way to do it directly from the code string, since some scanners have the option to prefix or suffix the code , it might be a great idea to have the option to sort the instances with that information.

Something like: 

```javascript
const scanner = BarcodeScanner({
  ...foo,
  devicePrefix: 'd1_',
  ...foo
});
```

And then filter the event only for the selected device.

I could do a pr if necessary but would like to know if it is a viable solution, thanks!

**Comment by hadeeb** [comment]
You could probably do this by creating a wrapper around this module.
```ts
import Scanner, { BarcodeScanner } from "simple-barcode-scanner";

export default function MultiDeviceBarcodeScanner(
  options: BarcodeScanner.Option & { devicePrefix?: string }
): BarcodeScanner.Scanner {
  const scannerInstance = Scanner(options);
  const prefix = options.devicePrefix || "";
  return {
    off: scannerInstance.off,
    on(handler: BarcodeScanner.HandlerFunction) {
      scannerInstance.on((code, e) => {
        if (code.startsWith(prefix)) {
          handler(code.slice(prefix.length), e);
        }
      });
    },
  };
}
```

**Comment by denyncrawford** [comment]
Thanks @hadeeb, I already opened a PR with similar code!! You can do the review if you want... It would be nice if the module supports it by default 😄!
