### ISSUE TITLE
Scanning always returns the same value

### ISSUE THREAD

**Issue by lorro** [hadeeb/simple-barcode-scanner#4]
Hi

I just installed your barcode scanner plugin but am getting some weird results whenever I scan a barcode. Whichever barcode, QR, ... I scan I'm always getting the following value: **055**

Any idea what could be the problem here?

Thanks

**Comment by hadeeb** [comment]
It could be
 - Browser does not support [KeyboardEvent.Key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#Browser_compatibility)
 - The hardware sends a special characters to indicate start/end of scanning.
Try adding a `keydown` event listener and log the output to see the keys used by your hardware and pass it in `endKeys` option to `BarcodeScanner` function.

Hope this helps
